spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.58:8848
        namespace: public
  application:
    name: product-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://140.143.161.107:3306/learn?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://192.168.0.58:3306/mall?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Q1w2e3r4t5-
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: cn.wwtianmei.qingyun.order.entity
dubbo:
  scan:
    base-packages: cn.wwtianmei.qingyun.product.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
      serialization: kryo
  registry:
    address: spring-cloud://192.168.0.58